### ISSUE TITLE
把MyUtil用Jitpack封装起来是不是更易用一些？

### ISSUE THREAD

**Issue by FlyingRadish** [tsy12321/LeanoteAndroid#1]

**Comment by tsy12321** [comment]
因为在开发中，还会不断修改，准备等开发阶段完成然后打包发布出去，现在暂时用submodule方便及时增加

**Comment by FlyingRadish** [comment]
似乎submodule用的是SSH link，在clone的时候会提示`Permission denied (publickey)`

**Comment by tsy12321** [comment]
对的。还没发布还属于开发中。2种方法
1. 把MyUtil下载下来直接引用
2. 把MyUtil也fork 然后submodule地址改成你自己fork的地址

**Comment by FlyingRadish** [comment]
另外请问一下，笔记浏览编辑这部分你打算怎么做呢？

**Comment by tsy12321** [comment]
准备用开源的markdown编辑器嵌进去。搜了下 有的
